# 线上配置文件
# @author <a href="https://github.com/liyupi">程序员鱼皮</a>
# @from <a href="https://yupi.icu">编程导航知识星球</a>
# 注意开源时这个文件不要提交、或者不要填真实配置
spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.120.11.50:3306/match?serverTimezone=Asia/Shanghai&useSSL=false
    username: match
    password: 123456
  # session 失效时间
  session:
    timeout: 86400
  redis:
    port: 6379
    host: 47.120.11.50
    database: 3
    password: 123456
    redissonDatabase: 4
server:
  address: 0.0.0.0
  port: 8010

# [编程知识星球](https://yupi.icu) 零基础快速入门编程，不走弯路！30+ 原创学习路线和专栏、1000+ 编程精华文章、500+ 编程学习指南、20T+ 编程资源汇总