server:
  port: 8010
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
        # 如果需要在两个端口或者两台服务器中共享Session（用户登录凭证）的话，需要开启下面的配置
#        domain: localhost
spring:
  profiles:
    active: dev
  application:
    name: jackpao-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/match?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  session:
    store-type: redis
    # 30 天过期
    timeout: 2592000
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # redis 配置

#  rabbitmq:
#    host: localhost
#    port: 5672
#    virtual-host: /
#    username: guest
#    password: guest
#    listener:
#      simple:
#        prefetch: 1 # 每次只能获取一条消息，处理完成才能获取下一跳消息
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
# 配置日志的时间格式
#logging:
#  pattern:
#    dateformat: MM-dd HH:mm:SS